### ISSUE TITLE
Issue with libjack-dev on ubuntu 20.04

### ISSUE THREAD

**Issue by rabidmachine9** [free-sm/geonkick#165]
Hey, 
libjack-dev seems to be needed in order to compile 
but it seems to be in conflict with many other packages that are using libjack1(and even jack2 seems to be among them)
is there something I am missing ? I do not really want to mess with my packages but I would like to use geonkick!

Thanks for any help :)

**Comment by iurienistor** [comment]
In the geonkick/CMakeLists.txt tun off the build for standalone if you want to use only the plugin (this will no more require to install libjack-dev). Otherwise you'll need to install libjack-dev. Under Ubuntu these packages has some conflict issues.

`option(GKICK_STANDALONE "Enable build for standalone" OFF)`

**Comment by iurienistor** [comment]
I have modified something in order if there is no libjack-dev installed than the standalone version will not be build, only the plugins

**Comment by rabidmachine9** [comment]
Hey, I forgot to reply, but I did manage to compile by disabling the flag! I also had to delete the cache in build folder before trying to run make. The fix sounds very useful, thank you sooo much!
