### ISSUE TITLE
Reaper Crash when moving notes while loop is playing

### ISSUE THREAD

**Issue by arumihsnek** [free-sm/geonkick#172]
Hi!

How to reproduce the bug:
1. Make a region in a track with Geonkick single.
2. Midi Editor > Options > Preview notes when editing or insert.
3. Play in loop this region (or a time selection)
4. Move (drag) or instert notes in midi editor or midi inline editor while the loop is playing
5. Wait for the crash.

Only happens with Geonkick, because that i think is a geonkick bug...

**Comment by iurienistor** [comment]
@arumihsnek Is this happening with VST3 or LV3 version of the plugin on Reaper?

**Comment by arumihsnek** [comment]
I don't know how to install the VST version of the plugin from the Arch repos... O.o

**Comment by iurienistor** [comment]
@arumihsnek 
I have committed in the master the fix for LV2 for Reaper. VST3 version doesn't crash in Reaper and it uses the same code where it crashes in LV2. My conclusion is that Reaper host has a little problem with LV2... I think the host is giving the wrong frames. In the next days I'll publish the fix as a release.

**Comment by iurienistor** [comment]
Released the fix https://github.com/free-sm/geonkick/releases/tag/v2.9.1
